### ISSUE TITLE
Qt Creator 4.10 build

### ISSUE THREAD

**Issue by GPBeta** [CJCombrink/SpellChecker-Plugin#104]
So, Qt Creator 4.10 is released, I'm looking forward to use this great plug-in with it :)

**Comment by CJCombrink** [comment]
Thanks for reaching out.
I am planning to spend tonight to build the plugin for Qt Creator 4.10. I had infrastructure problems last night so could unfortunately not do it. 
Quick question, which platform are you using it, if I have limited time I will start with the platform you require.
(I am planning to improve my build/release process to get updates out faster in future, not sure when I will get time for that though)

**Comment by GPBeta** [comment]
Thanks for the responsive, I'm using it on 64 bit Windows 10 with 32 bit official pre-built Qt Creator.

**Comment by CJCombrink** [comment]
(phew)
The one I also use most
I will try my best to have it available by the end of my day (22:00 GMT+2)

**Comment by CJCombrink** [comment]
@GPBeta I have just released version 2.0.3 for Qt Creator 4.10.

Let me know if there are any issues.
