### ISSUE TITLE
Unknown error 0x000000c1.

### ISSUE THREAD

**Issue by Gpinchon** [CJCombrink/SpellChecker-Plugin#106]
When I try to run QtCreator with SpellChecker, it complains about not being able to load SpellChecker4.dll with an unknown error 0x000000c1.
Qt Creator version : 4.10.0
Windows version : 10 Pro 1903 Build 18362.356
SpellChecker version : 2.0.3

**Comment by CJCombrink** [comment]
Did you copy the libhunspell.dll file bundled with the plugin into the bin folder of Qt Creator (where the qtcreator.exe file is)?

**Comment by CJCombrink** [comment]
What could also go wrong, you must ensure that the architecture of the plugin matches the one of Qt Creator (64 bit vs 32 bit).
In QtCreator this can be checked by going to "Help" -> "About Qt Creator" it should list something like:
```
Based on Qt 5.13.1 (MSVC 2017, 32 bit)
```
The "X bit" part should match the version of the plugin that was downloaded.

**Comment by Gpinchon** [comment]
Oh yeah, I used the x64 libs instead of the x86 ones.
My OS is x64, thus the confusion. Maybe it would be good to specify in the Readme that the library architecture should match the one of Qt Creator and not the one of the OS ?

**Comment by CJCombrink** [comment]
No problem, thanks for using the plugin in reaching out.
Nope, not a fool, honest mistake. If you have any suggestions on how this can be emphasized please let me know, or for that matter any suggestions or comments.
