### ISSUE TITLE
ubuntu 19.10 - libhunspell 1.7 

### ISSUE THREAD

**Issue by drozel** [CJCombrink/SpellChecker-Plugin#107]
Tried to install prebuild binaries on QtCreator 4.10.1 on Ubuntu 19.10 - couldn't find libhunspell 1.6.
I have created the symlink to the new 1.7 .so, installed the dicts, everything started but shows all words as wrong.

I suspect, symlink creating is wrong and plugin should support libhunspell 1.7

**Comment by CJCombrink** [comment]
@drozel 
Sorry for the long delay. 
Is it possible for you to test the attached plugin with QtCreator 4.11 - RC1 on Ubuntu 19.10?
[SpellChecker-Plugin_v2.0.4_x64.tar.gz](https://github.com/CJCombrink/SpellChecker-Plugin/files/3928541/SpellChecker-Plugin_v2.0.4_x64.tar.gz)

**Comment by CJCombrink** [comment]
@drozel 
I have published the latest release for Qt Creator 4.11 using a static build of hunspell. Please test on 19.10 and let me know how it went. For now I am closing the issue but will re-open if there are issues.

**Comment by drozel** [comment]
sorry for long delay too.
It works, thank you very much!
