### ISSUE TITLE
Spell check commit message too

### ISSUE THREAD

**Issue by jesperkdab** [CJCombrink/SpellChecker-Plugin#111]
I love this plugin, no less!
Would be nice if it would be enabled for git commit message (press Alt-g+Alt-c)

Thanks
Jesper.

**Comment by CJCombrink** [comment]
Unfortunately the plugin is only checking C++ sources and headers.
Something like this is unfortunately not a priority but it would surely be nice to have, but not seeing it happen any time soon.
