### ISSUE TITLE
QtCreator 4.12.0?

### ISSUE THREAD

**Issue by javier-box** [CJCombrink/SpellChecker-Plugin#112]
Are there any plans to compile a new version for 4.12.0(current release)?

**Comment by youmych** [comment]
Yep, could you provide the plugin for QtCreator 4.12.0?

**Comment by CJCombrink** [comment]
Hi, sorry about the delay.

I will see if I can't get the time to build releases as soon as possible. 
Quick question, what OS's are you using the plugin on so that I can focus on getting a release out for those first?

**Comment by Tobi2001** [comment]
> 
> 
> Hi, sorry about the delay.
> 
> I will see if I can't get the time to build releases as soon as possible.
> Quick question, what OS's are you using the plugin on so that I can focus on getting a release out for those first?

I'd be happy about a release for Ubuntu 18.04.

**Comment by pcipriano** [comment]
Happy to have it for Windows.

**Comment by youmych** [comment]
I prefer using QtCreator on Linux Mint)

**Comment by CJCombrink** [comment]
Quick update: I could get my development machine set up, installed and rebuild most that is needed. All that I now need to do is try to update and make a new release, that should happen hopefully tonight.

**Comment by CJCombrink** [comment]
I have published a release, please test and let me know how it is going. 
Again sorry for the delay.
