### ISSUE TITLE
Plugin for QtC 4.13 on MAc seems to be empty

### ISSUE THREAD

**Issue by arunpkqt** [CJCombrink/SpellChecker-Plugin#118]
I could not extract the file `SpellChecker-Plugin_QtC4.13_macos_x64.tar.gz` Seems to be empty.

**Comment by CJCombrink** [comment]
@arunpkqt I see that, and it is quite obvious. 
I will see if I can investigate in the next few days, hopefully it is something simple to solve in the pipeline script.

**Comment by CJCombrink** [comment]
@arunpkqt 
I think I found the issue, can you please test the archive created as part of the latest action run: https://github.com/CJCombrink/SpellChecker-Plugin/actions/runs/280913680

**Comment by arunpkqt** [comment]
Cool, that worked.

**Comment by CJCombrink** [comment]
@arunpkqt 
Is the plugin working as intended on Mac?

If possible, do you perhaps mind sharing some screenshots, I do not have a (legal) way to test on Mac thus is very curious on how it looks and behave.

**Comment by arunpkqt** [comment]
@CJCombrink Yes. It is working as expected.

<img width="949" alt="SpellChecker_ScreenGrab" src="https://user-images.githubusercontent.com/4667704/95175974-7f8b1700-07bc-11eb-98ae-4243ad71dc9d.png">

<img width="1096" alt="Screenshot 2020-10-06 at 10 14 08" src="https://user-images.githubusercontent.com/4667704/95176204-d395fb80-07bc-11eb-89f1-c4439c24e5bd.png">

**Comment by CJCombrink** [comment]
@arunpkqt 
Awesome, thanks for taking the time to log the issue, respond and upload the screens, it is much appreciated.
