### ISSUE TITLE
Release link leads to 404

### ISSUE THREAD

**Issue by marcelpetrick** [CJCombrink/SpellChecker-Plugin#126]
Greetings,
wanted to get the release for QtC 4.15, but this https://github.com/CJCombrink/SpellChecker-Plugin/blob/master/releases leads to a 404 page.
Not sure what went wrong. But for the 4.14 release it was existing.

**Comment by CJCombrink** [comment]
Thanks for reporting
I still need to follow up on that issue, not sure why it broke
Try the link from the "Releases" link on the right on GitHub: https://github.com/CJCombrink/SpellChecker-Plugin/releases (not the one in the readme)

**Comment by CJCombrink** [comment]
The "Releases" link in the readme should work again
