### ISSUE TITLE
Qt Creator 8.0.0 switch to the new MIME database implementation.

### ISSUE THREAD

**Issue by tuantran1632001** [CJCombrink/SpellChecker-Plugin#139]
Build the plugin with Qt Creator 8.0.0 will result in the following errors:
```
SpellChecker-Plugin-3.0.0/src/Parsers/CppParser/cppdocumentparser.cpp:44:10: fatal error: utils/mimetypes/mimedatabase.h: No such file or directory
   44 | #include <utils/mimetypes/mimedatabase.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The 8.0.0 version of Qt Creator switch to the new MIME database implementation which is at `utils/mimetypes2/mimedatabase.h`. I have not tried to test with it, though.

**Comment by CJCombrink** [comment]
@tuantran1632001 

Thank you for the report.
It should be fixed in the latest commits on master.

PS: the release for Qt Creator 8.0 is busy building and should be available in about an hour from now from the Releases page.
