### ISSUE TITLE
Document that pressing Alt+Enter on a wrong spelled word give correction options

### ISSUE THREAD

**Issue by miemoe** [CJCombrink/SpellChecker-Plugin#147]
Just by "wild guessing" I realized, that having the cursor on a wrongly spelled word in a comment an pressing Alt+Enter gives me a tooltip to select a corrected word / ignore it / add it to user defined.
Great!

This "triggering" should be in the README.md!

**Comment by CJCombrink** [comment]
@miemoe Thanks for the feedback.
Sorry for only responding now. 
I did update the README, please re-open if you have better suggestions (or a better way to put it)
I also added a gif to the [wiki](https://github.com/CJCombrink/SpellChecker-Plugin/wiki#quick-fix-menu) page with an explicit link to the wiki in the readme. 
It seems like people does not know that there is a small write up there

**Comment by miemoe** [comment]
Thanks for the update / info

On the wiki page the "video" of the Alt+Enter is nice.
However, using the mouse to select the right spelling is somehow slowing down the editing process:
maybe you replace the video with keyboard action (cursor down) or even the spin around (cursor up) to have a shortcut to "Add to dictionary" or "Ignore word".

**Comment by CJCombrink** [comment]
Thanks for the suggestion, I will see what I can do.
As far as I know the arrows for up and down should work.

_Fun fact: the up and down arrows on my keyboard is not working anymore thus I could not use them for the video :(_
