### ISSUE TITLE
Any plans to support QtCreator 12

### ISSUE THREAD

**Issue by miemoe** [CJCombrink/SpellChecker-Plugin#152]
Hi,

as QtCreator 12 seems to be published soon (RC1 is already available) ...

Are there any plans to adapt the plugin to this new Creator?
Or will it work, out-of-the-box with the last tag?

Well, just tried it with no luck:
![image](https://github.com/CJCombrink/SpellChecker-Plugin/assets/63240461/f25cdcbc-b25e-4af2-ae92-321cdf0bcedd)

Kind regards,
Michael

**Comment by CJCombrink** [comment]
@miemoe 

Thanks for reaching out. 

I am definitely planning to support Qt Creator 12, I just did not have time to see how much effort it would be.
I will try to see if I can get started tonight.

> Or will it work, out-of-the-box with the last tag?

Unfortunately it will definitely not work out of the box due to the way Qt Creator does versioning. At the very least it would require a rebuild, but I suspect it would involve a bit more API adapting etc.

**Comment by CJCombrink** [comment]
@miemoe I made great strides the last two evenings to get Qt Creator 12 support in place. 
Unfortunately I had to spend most of my night last night on work work but I at least got the new artifacts to be built. 

There is still a bug with the the 'ignore word' icon (the minus) but apart from that it looks functional. 

If you need one urgently you can see if you can download the correct version from the [actions](https://github.com/CJCombrink/SpellChecker-Plugin/actions) page. (It might be double compressed though). If not please let me know and I will see if I can't make a plan.

I am planning to solve the bug tonight (about 15hours from now) and then do more thorough testing.

Sorry for the delay.

**Comment by miemoe** [comment]
@CJCombrink Great to hear, that you had great progress.

As I'm not so familiar with these "actions" I finally found a window version on: https://github.com/CJCombrink/SpellChecker-Plugin/actions/runs/6974549135
I hope this is the right version?

I looked into the zipped zip :-) and found the SpellChecker.dll.
Last time there was a bin folder along with the hunspell-1.7-0.dll inside. Are you planning to put this into the final zip for windows? Or is there even a newer one that might be deployed?

Anyway, thanks again for your nice work.

ps: no reason to feel sorry

**Comment by CJCombrink** [comment]
@miemoe 

> found a window version on

Yes that is the correct one

> there was a bin folder

For this version I switched from vcpkg to conan and the conan default is static linking. What that means is there is no more bin folder needed for Windows. I am planning to test some more but am very optimistic about this change.

If all goes well I will have a release shortly

**Comment by CJCombrink** [comment]
@miemoe I created the release: [v3.5.0](https://github.com/CJCombrink/SpellChecker-Plugin/releases/tag/v3.5.0)

I am closing this issue, please open new ones if you encounter any issues.

**Comment by miemoe** [comment]
I just gave a quick test.

Up to now everything looks nice.

Thanks a lot for your prompt action!
