### ISSUE TITLE
Add QtCreator v14 support

### ISSUE THREAD

**Issue by silverqx** [CJCombrink/SpellChecker-Plugin#161]
Can you already release a new version that will support qtc14?

**Comment by CJCombrink** [comment]
Hi @silverqx 

Unfortunately it is not as easy with Qt Creator.
If I would release a new version that works for the Beta 2 just released I will have to re-release for 14 when it finally gets released.

The way I release and the way Qt release also makes it very hard to just release for an RC or Beta, in the past it was better but somewhere something changed and I have not yet put in the time to try and support both.

I will definitely spend the time to make a release as soon as it is officially released.
I will try to see what I can get done regarding getting ready for when they release regarding the compatibility and the PRs open. 
But until there is an official release I can't promise anything.

**Comment by silverqx** [comment]
Ok, thx for the explanation, it looks like you would need to release for every pre-release and also for GA which is of course too much, the only way would be to automate this somehow.

**Comment by silverqx** [comment]
Hi, v15 beta is out so I tried to build myself.

I want to ask if this is really needed:
```shell
-DCMAKE_INCLUDE_PATH='E:/Qt/Tools/Qt Creator 15.0.0-beta2/include/qtcreator/src/libs/3rdparty/syntax-highlighting/autogenerated/include'
```

**Comment by silverqx** [comment]
I tried with and without it, and it compiles, but I want to know if some features, e.g., will be disabled without it.
