### ISSUE TITLE
Qt Creator 15 is missing Spell Checker

### ISSUE THREAD

**Issue by miemoe** [CJCombrink/SpellChecker-Plugin#169]
Hi,

as I really like to use your Spell Checker as plugin in Qt Creator,
I would like to ask, if there are any plans in releasing an updated version that will work with
Qt Creator 15.

Would be great to have it working.

Kind regards,
Michael

**Comment by CJCombrink** [comment]
Hi @miemoe 

Sorry I have not yet made the release, I will try tonight

**Comment by CJCombrink** [comment]
Release out for Qt Creator 15.
Sorry for the delay and thanks for the patience 👍

**Comment by miemoe** [comment]
Installed und checked on Qt Creator 15 under Ubuntu 20.04.
Works perfectly for me.
Thanks a lot four your effort.
