### ISSUE TITLE
2 Character Misalignment Between Underlining and Misspelled Word

### ISSUE THREAD

**Issue by jasonnicholson** [CJCombrink/SpellChecker-Plugin#28]
# Qt Creator Informaiton
Qt Creator 3.3.0 (opensource)
Based on Qt 5.4.0 (MSVC 2010, 32 bit)
Built on Dec 8 2014 at 15:24:21
From revision d36c4d87db

# OS information
Windows 7 x64

# SpellChecker-Plugin
0.2.1

# Problem
The underlined misspelled word is offset by two characters (1st picture).  This causes issue when replacing a misspelled word (2nd picture).  

Before word replacement:
![before word replacement](https://cloud.githubusercontent.com/assets/1058191/5886090/eae29a8e-a34d-11e4-8fab-fcfa2a8d3eed.jpg)

After Word Replacement:
![after word replacement](https://cloud.githubusercontent.com/assets/1058191/5886095/409fe2ce-a34e-11e4-9f5d-ab0e14c85b0e.jpg)

# Sample Text Used
This is the sample text that I used.  It came from 2nd paragraph [here](https://www.gutenberg.org/cache/epub/1661/pg1661.txt).  

    /* 
    I had seen little of Holmes lately. My marriage had drifted us
    away from each other. My own complete happiness, and the
    home-centred interests which rise up around the man who first
    finds himself master of his own establishment, were sufficient to
    absorb all my attention, while Holmes, who loathed every form of
    society with his whole Bohemian soul, remained in our lodgings in
    Baker Street, buried among his old books, and alternating from
    week to week between cocaine and ambition, the drowsiness of the
    drug, and the fierce energy of his own keen nature. He was still,
    as ever, deeply attracted by the study of crime, and occupied his
    immense faculties and extraordinary powers of observation in
    following out those clues, and clearing up those mysteries which
    had been abandoned as hopeless by the official police. From time
    to time I heard some vague account of his doings: of his summons
    to Odessa in the case of the Trepoff murder, of his clearing up
    of the singular tragedy of the Atkinson brothers at Trincomalee,
    and finally of the mission which he had accomplished so
    delicately and successfully for the reigning family of Holland.
    Beyond these signs of his activity, however, which I merely
    shared with all the readers of the daily press, I knew little of
    my former friend and companion.
    */

**Comment by CJCombrink** [comment]
Hi,

This is very strange, given the above text everything seems to be working fine on my side:
![spellchecker_issue28](https://cloud.githubusercontent.com/assets/1647870/5888706/2d09f55e-a413-11e4-8d90-6b140b181e8b.png)

My setup is exactly the same as yours as far as I can tell, same QtC, Plugin Version, Win7x64 

Is the issue in all source files or just in the one? If all sources, all projects? 
Is there a possibility to send me the original file?

**Comment by jasonnicholson** [comment]
I don't think it is file related because happened in every file.  The original file was irrelevant.

The problem consistent I found out today.  It does not occur on my home computer.  The error I reported above came from my work computer.

**Comment by CJCombrink** [comment]
Is there any reason why it would differ between the work and home PC?
Did you attempt to open the same project on both?

**Comment by jasonnicholson** [comment]
The project was the same on both computers.  It is not obvious to me yet what the issue is.  I will try to gather information as to why there is a difference over the next few days.

**Comment by jasonnicholson** [comment]
I can't post the code that produces the  problem.  Can we somehow connect via a private message so that I can provide you with a sample project?

I was able to produce the problem on Linux with the same project files as my other two computers.  I am really confused on what is causing the issue.

Sincerely,
Jason Nicholson
jashale 
at 
yahoo

**Comment by CJCombrink** [comment]
Jason,

I have identified the issue and it is due to the character 'ö' in the comments before the issue. 

I have sent an email to the QtCreator mailing list to try and resolve this issue (as you should have seen).

I will keep an eye on the answers and in the mean time try to see what else I can do regarding this. I will update as soon as I have a proper solution. 

Thank you very much for your help so far, sorry for this issue.

**Comment by jasonnicholson** [comment]
Carel,
Good work!  Thank you for your help!!
This past weekend I spell checked about ~2000 C++ source files and made changes in 587 files using Notepad++.  This was about 20hours of work.  The problem is mostly due to the development team using QtCreator without the support of spell check.  The problem cascades into the documentation generated by Doxygen from the C++ source which then is seen by the customer base.  I am hoping that your plugin fixes this ongoing issue.  Again, thank you!
 Sincerely,
Jason Nicholson 

     On Tuesday, January 27, 2015 1:13 PM, Carel <notifications@github.com> wrote:
   

 Jason,I have identified the issue and it is due to the character 'ö' in the comments before the issue. I have sent an email to the QtCreator mailing list to try and resolve this issue (as you should have seen).I will keep an eye on the answers and in the mean time try to see what else I can do regarding this. I will update as soon as I have a proper solution. Thank you very much for your help so far, sorry for this issue.—

**Comment by CJCombrink** [comment]
Hi Jason,

Please get the latest release from the releases page (0.3.0), it should have the fix in for the mentioned issue. 

My setup was not correct to get a Linux build completed but I wanted to get the Windows fix to you as soon as possible. If you can test it I would appreciate it a lot. 

Please let me know if there are any other issues.
