### ISSUE TITLE
Show right click menu when right click in "Spelling Mistakes" pane.

### ISSUE THREAD

**Issue by JPNaude** [CJCombrink/SpellChecker-Plugin#30]
It will be nice if the "Spell Check" menu that pops up when you right click on a misspelled word in the editor can also pop up when you right click on a mistake in the bottom "Spelling Mistakes" pane.

**Comment by JPNaude** [comment]
The right click menu is also not available in the navigation widget.

**Comment by CJCombrink** [comment]
I can see that the right click menu can be useful on the output pane but don't see how it would be helpful on the navigation widget, what do you see it doing when you right click on the navigation widget?
