### ISSUE TITLE
Misspelled words are not underlined in non cpp files.

### ISSUE THREAD

**Issue by JPNaude** [CJCombrink/SpellChecker-Plugin#31]
I have some .tcl files in my project.
The spelling mistakes in them are picked up, but they are not underlined in the editor. Also, the "Spell Check" menu is not available for them.

**Comment by CJCombrink** [comment]
This seems to be a bug, but the sad news is the bug is that it checks the .tcl files...

The parser is only supposed to parse C++ related files, *.cpp and *.h. I will have to see why it tries to parse the tcl file and perhaps make it a feature not directly related to the cpp parser.
