### ISSUE TITLE
Ignore big files

### ISSUE THREAD

**Issue by patplan** [CJCombrink/SpellChecker-Plugin#57]
Since I have to maintain often old code, where files have sometimes more the 8000 LOC. The SpellChecker-Plugin works great, but on such big files, it blocks the Qt-Creator often  for seconds. When I have to edit such files, I always need to disable the plugin.

It would be great to have an option, that the spell checker ignores files over a specific size (Bytes or Lines)

**Comment by CJCombrink** [comment]
Hi,

A while back I made a few changes to try and speed up checking big files. The checker will unfortunately have to spend the time the first time to parse the file, thereafter it _should_ be faster. The actual speedup will depend on the file contents. 

Adding an option to ignore a file should not be too much of an effort. 

What is the possibility for you to send me one of those big files?

**Comment by patplan** [comment]
Hey,
sorry, I am not allowed to send you a file out of our code. But I can reproduce it with an other file, which are big. Like this one: [qwidget.cpp of Qt4.8](http://code.metager.de/source/xref/lib/qt/src/gui/kernel/qwidget.cpp)
After typing just a few chars, it blocks for seconds...

**Comment by CJCombrink** [comment]
I have made some changes for version 2.0.0 of the plugin that should improve the situation with big files.

I am closing this issue. If it is still a problem please let me know and I will re-open.

**Comment by patpat2** [comment]
works perfectly now. Thank you!
