### ISSUE TITLE
Release for Qt Creator 4.5.0

### ISSUE THREAD

**Issue by martinkirsche** [CJCombrink/SpellChecker-Plugin#78]
A release that got compiled for Qt Creator 4.5.0 is still missing.

Please tell me if I can somehow help with that task.

**Comment by CJCombrink** [comment]
Hi @martinkirsche 

I was on holiday when 4.5 got released until yesterday. I will have the release out by end of the week if that is ok.

**Comment by martinkirsche** [comment]
That’s perfectly fine. I just thought that this got forgotten or will somehow not be done by you anymore.

Thanks for all your efforts.

**Comment by CJCombrink** [comment]
@martinkirsche 
I have just finished the release, please test and let me know if there are any problems.
