### ISSUE TITLE
Does not load with Qt Creator 4.5.1

### ISSUE THREAD

**Issue by martinrotter** [CJCombrink/SpellChecker-Plugin#81]
```
C:\Qt\Tools\QtCreator\lib\qtcreator\plugins\SpellChecker4.dll: Cannot load library C:\Qt\Tools\QtCreator\lib\qtcreator\plugins\SpellChecker4.dll: Module not found.
```

**Comment by CJCombrink** [comment]
Please check to make sure that the `libhunspell.dll` is found in the bin folder of QtCreator:
"C:\Qt\Tools\QtCreator\bin\libhunspell.dll"

**Comment by martinrotter** [comment]
Yes now it works. It was not obvious that `libhunspell.dll` should be placed to "bin" folder instead of "plugins" folder.

**Comment by CJCombrink** [comment]
@martinrotter thanks for the update, any suggestion on where or how I can make this more obvious?

**Comment by martinrotter** [comment]
Well, it is written in readme, but for me, it would make sense to include relevant subfolders directly into the release zip, so that it looks like:
* bin\libhunspell.dll
* lib\qtcreator\plugins\SpellChecker4.dll
This way, user just grabs all folders from zip file and directly copies into Qt Creator **root** directory and thats it.

Just a suggestion, though.

**Comment by CJCombrink** [comment]
I have also considered that at one point. 
I will try this for the next release (if I remember, thus opening as issue) and see how it goes.

**Comment by CJCombrink** [comment]
I have started packaging the release as you have suggested thanks. It works better for me at least.

Closing the issue.
