### ISSUE TITLE
v1.1.0 doesn't work on Ubuntu 14 due to libhunspell-1.6.so.0 missing

### ISSUE THREAD

**Issue by moberhuber** [CJCombrink/SpellChecker-Plugin#83]
In the v1.1.0 release archive for Ubuntu, libSpellChecker.so has been linked against libhunspell-1.6.so.0. But Ubuntu 14.04 "trusty" as well as Ubuntu 16.04 "xenial" come with libhunspell-1.3, therefore the plugin doesn't work.

As a workaround, I have compiled hunspell-1.6.2 from source. Extracting attached [libhunspell-1.6.zip](https://github.com/CJCombrink/SpellChecker-Plugin/files/1815896/libhunspell-1.6.zip) into the lib/qtcreator/plugins folder, it works fine.

Making it work reliably on Ubuntu-14 was hard, since libSpellChecker is compiled using c++11 ABI Strings; but on Ubuntu 14, the c++11 ABI is turned off hardcoded in the system (-D_GLIBCXX_USE_CXX11_ABI=0 doesn't work). I ended up building hunspell on Ubuntu-16.04.2 with libstdc++ statically linked into hunspell. Which also required manual interaction, since the hunspell build system's libtool disables the -static-libstdc++. The following worked:
```
git clone https://github.com/hunspell/hunspell.git
cd hunspell
git checkout v1.6.2
autoreconf -vfi
CXXFLAGS='-static-libstdc++ -static-libgcc' ./configure
make
cd src/hunspell
g++ -fPIC -DPIC -shared -static-libstdc++ -static-libgcc .libs/affentry.o .libs/affixmgr.o .libs/csutil.o .libs/hashmgr.o .libs/hunspell.o .libs/suggestmgr.o .libs/phonet.o .libs/filemgr.o .libs/hunzip.o .libs/replist.o   -L/usr/lib/gcc/x86_64-linux-gnu/5 -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/5/../../.. -Wl,-soname -Wl,libhunspell-1.6.so.0 -o .libs/libhunspell-1.6.so.0.0.1
cp .libs/libhunspell-1.6.so.0.0.1 ./libhunspell-1.6.so.0
strip libhunspell-1.6.so.0
zip libhunspell-1.6.zip libhunspell-1.6.so.0
```
I don't know how exactly the plugin is built to be compatible with Qt Creator on all architectures, and if it is possible building against the older system-provided libhunspell-1.3; but I suppose the most generic solution is just adding the libhunspell-1.6.so.0 into the release archive for libSpellChecker-v1.1.0 and/or cutting a new v1.1.1 release with the missing lib added.

Thanks!

**Comment by CJCombrink** [comment]
Thanks for all the effort and the update.

I was afraid of this problem on Linux, but until now it seems like it was never an issue, thus I did't think much of it. 
Unfortunately I normally use the latest version of Ubuntu to build and release the Linux version, thus the reason for the version used. 

If I build libhunspell manually on Ubuntu 17.10 (or later versions since 18.04 is due to be released) using the above instructions I am assuming that it should also work on 14.04?

**Comment by moberhuber** [comment]
Hi Carel,

I'm afraid if you build on a newer version of any Linux OS, you can never guarantee that it will run on older versions. It _may_ work if your software happens to reference only system library APIs that used to exist in the older version already. But those system library APIs do evolve sometimes, and then it won't run on the older version.

You can reduce the risk by statically linking the libstdc++, as my instructions do. But I still link libc.so.6 dynamically, so your Ubuntu 17.10 _could_ theoretically pull in an API that 14 doesn't have. I've seen that in the past, you may read https://bugs.eclipse.org/bugs/show_bug.cgi?id=515155 if you are interested. I don't know if linking the libc statically as well is a good option to avoid that risk.

Bottomline, you'll need a tester on the older OS to be sure. Fortunately this is fairly easy these days thanks to virtualbox. In addition to that, there is also two fairly simple sanitychecks you can try. You can check the sharedlibs that your plugin requires:
`ldd libSpellChecker*.so`
Running this ldd command on the (old) target system, you'll see unresolved sharedlibs printed as 'not found'. If they also aren't available via apt-get, you'll need to avoid them. Or link them statically, or ship them yourself (happened so with libhunspell-1.6 in this case, which Ubuntu 14 doesn't provide).

Then, print the symbols that your plugin requires, for example:
`objdump -T libSpellChecker*.so | grep UND | grep -v Qt_5`

then compare against what your desired lowest version system has:
`objdump -T /lib/x86_64-linux-gnu/libc.so.6`
`objdump -T /usr/lib/x86_64-linux-gnu/libstdc++so.6`

My Ubuntu 14.04.5 has up to `GLIBC_2.18` and `CXXABI_1.3.11`. So if your library's undefined symbols have nothing newer it's a simple and fairly reliable check that it should work alright. If you do find newer symbols, you'll have to avoid them (like in the Eclipse example mentioned before), or statically link, or resort to building on the older Linux.

Now that's become a long post :) let me know if you have any more questions, I'll try to help if I can.

**Comment by moberhuber** [comment]
I just noticed that the binary download of Qt Creator 4.6 itself is "Based on Qt 5.10.1 (GCC 5.3.1 20160406 Red Hat 5.3.1-6 64-bit)". So if you want the SpellCheckerPlugin to be usable across the widest possible range of Linux distributions, it would be best building the plugin as well as libhunspell from source on a RedHat / CentOS-5.3.1 host with GCC-5.3.1. I think that's the easiest way making sure it runs wherever Qt Creator itself can run.

**Comment by CJCombrink** [comment]
@moberhuber I have started building the release on Ubuntu 16.04 as well as 18.04, did you perhaps have a chance to test if the one for 16.04 works on Ubuntu 14.04 if it is still needed?

For now I am closing this issue, but if this is still a problem please comment on the issue.
