### ISSUE TITLE
unable to use non-english dictionaries

### ISSUE THREAD

**Issue by vic-prog** [CJCombrink/SpellChecker-Plugin#92]
Dictionaries taken from
https://github.com/wooorm/dictionaries/tree/master/dictionaries/ru
seems not working.
A lot of mistakes like
<img width="209" alt="screenshot_1" src="https://user-images.githubusercontent.com/11266380/43033232-348efd4e-8ccf-11e8-96cf-30e157196426.png">
and in speell-checking-errors-list errors looks strange
<img width="257" alt="screenshot_2" src="https://user-images.githubusercontent.com/11266380/43033237-50045006-8ccf-11e8-81a2-6d7bcb0cf04d.png">
Dictionaries downloaded from github correctly. In QtCreator they look reasonably good
<img width="263" alt="screenshot_3" src="https://user-images.githubusercontent.com/11266380/43033254-ce492ec8-8ccf-11e8-88a8-55c0921885cb.png">
and
<img width="263" alt="screenshot_4" src="https://user-images.githubusercontent.com/11266380/43033257-d2b19892-8ccf-11e8-9981-4817d736c1e5.png">
This dictionary is selected in proprties of plugin
<img width="303" alt="screenshot_5" src="https://user-images.githubusercontent.com/11266380/43033292-78f599f6-8cd0-11e8-914c-321f464cc83f.png">
QtCreator is 4.7.beta2
<img width="367" alt="screenshot_6" src="https://user-images.githubusercontent.com/11266380/43033302-a1824464-8cd0-11e8-969e-fa626dab6d10.png">
Prebuild spellchecking plugin was taken from github releases
SpellChecker-Plugin_v1.2.83_x64.zip
English dictionaries from
https://github.com/wooorm/dictionaries/tree/master/dictionaries/en
are  working fine!

**Comment by CJCombrink** [comment]
@vic-prog 
Thanks for taking the time to test the plugin and and report. 
Although I only use English why it should not work. 

Is it perhaps possible to create an example file that reproduces the issues that you mention, zip it together with the dictionary that you use and attach to the issue. This would be the best for me to try and diagnose the issue.

**Comment by rdnvndr** [comment]
The version 1.3 Release for QtCreator 4.7 works

**Comment by CJCombrink** [comment]
@rdnvndr I am closing this issue as it seems like it is resolved.
Thanks for testing and using, if you are not aware I have released a new version (v2.0.0) that you can test and provide feedback as required.
